Repository ImpectAPI/impectPy, pull requests merged in 2025-05, with the labels that each got.

#82 79 add fifa country name to several functions
  impectPy/iteration_averages.py
  impectPy/iterations.py
  impectPy/matchsums.py
  impectPy/player_profile_scores.py
  impectPy/player_scores.py
Labels: enhancement

#83 handle missing shirt number properly
  impectPy/match_info.py
Labels: bug

#84 Release
  impectPy/iteration_averages.py
  impectPy/iterations.py
  impectPy/match_info.py
  impectPy/matchsums.py
  impectPy/player_profile_scores.py
  impectPy/player_scores.py
Labels: release new version

#85 bump version
  NEWS.md
  README.md
  setup.py
Labels: release new version

#86 80 change code tag even more3
  impectPy/__init__.py
  impectPy/sportscode_xml.py
Labels: enhancement, xml

#87 63 change code tag to variable
  impectPy/__init__.py
  impectPy/sportscode_xml.py
Labels: enhancement, xml
